# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=75)),
                ('product_detail', models.CharField(max_length=200)),
                ('product_id', models.IntegerField()),
                ('category_id', models.CharField(max_length=45)),
                ('unit_in_stock', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('color', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
