# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category_ID',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_detail',
            new_name='product_Detail',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='product_ID',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='product_Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='unit_Price',
        ),
    ]
