# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170925_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_06', models.IntegerField(default=0)),
                ('size_07', models.IntegerField(default=0)),
                ('size_08', models.IntegerField(default=0)),
                ('size_09', models.IntegerField(default=0)),
                ('size_10', models.IntegerField(default=0)),
                ('size_11', models.IntegerField(default=0)),
                ('size_12', models.IntegerField(default=0)),
                ('size_13', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('logo', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='size',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
