# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170925_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ID',
            field=models.CharField(max_length=45),
        ),
    ]
