# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170925_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'sizes'},
        ),
    ]
