# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170925_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.CharField(max_length=45)),
                ('order_Date', models.DateTimeField(verbose_name='date ordered')),
                ('address_to_send', models.CharField(max_length=200)),
                ('paid', models.BooleanField()),
                ('date_send', models.DateTimeField(verbose_name='date delivered')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OrderBy')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('unit', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='size',
            name='product_ID',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='History',
            new_name='stripe_key',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit_in_stock',
            new_name='size_06',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='company_name',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='product_Name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_ID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_Detail',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_ID',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='size_06_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_07',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_07_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_08',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_08_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_09',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_09_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_10_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_11_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_12_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size_13_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ID',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Name',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='ordertemp',
            name='customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer'),
        ),
        migrations.AddField(
            model_name='ordertemp',
            name='order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OrderBy'),
        ),
        migrations.AddField(
            model_name='ordertemp',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='orderby',
            name='customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer'),
        ),
    ]
