# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170928_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
    ]
