# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random', models.CharField(default='0.8632043430865047', max_length=45)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
    ]
