# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_getnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getnumber',
            name='product_ID',
        ),
        migrations.DeleteModel(
            name='GetNumber',
        ),
    ]
