# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_profile_pic'),
        ('main', '0014_auto_20170930_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_ID', models.CharField(default='', max_length=45)),
                ('date', models.DateTimeField()),
                ('topic', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=2000)),
                ('pic', models.FileField(blank=True, null=True, upload_to='')),
                ('source', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Prod360',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.FileField(blank=True, null=True, upload_to='')),
                ('pic2', models.FileField(blank=True, null=True, upload_to='')),
                ('pic3', models.FileField(blank=True, null=True, upload_to='')),
                ('pic4', models.FileField(blank=True, null=True, upload_to='')),
                ('pic5', models.FileField(blank=True, null=True, upload_to='')),
                ('pic6', models.FileField(blank=True, null=True, upload_to='')),
                ('pic7', models.FileField(blank=True, null=True, upload_to='')),
                ('pic8', models.FileField(blank=True, null=True, upload_to='')),
                ('pic9', models.FileField(blank=True, null=True, upload_to='')),
                ('pic10', models.FileField(blank=True, null=True, upload_to='')),
                ('pic11', models.FileField(blank=True, null=True, upload_to='')),
                ('pic12', models.FileField(blank=True, null=True, upload_to='')),
                ('pic13', models.FileField(blank=True, null=True, upload_to='')),
                ('pic14', models.FileField(blank=True, null=True, upload_to='')),
                ('pic15', models.FileField(blank=True, null=True, upload_to='')),
                ('pic16', models.FileField(blank=True, null=True, upload_to='')),
                ('pic17', models.FileField(blank=True, null=True, upload_to='')),
                ('pic18', models.FileField(blank=True, null=True, upload_to='')),
                ('pic19', models.FileField(blank=True, null=True, upload_to='')),
                ('pic20', models.FileField(blank=True, null=True, upload_to='')),
                ('pic21', models.FileField(blank=True, null=True, upload_to='')),
                ('pic22', models.FileField(blank=True, null=True, upload_to='')),
                ('pic23', models.FileField(blank=True, null=True, upload_to='')),
                ('pic24', models.FileField(blank=True, null=True, upload_to='')),
                ('pic25', models.FileField(blank=True, null=True, upload_to='')),
                ('pic26', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Prod4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.FileField(blank=True, null=True, upload_to='')),
                ('pic2', models.FileField(blank=True, null=True, upload_to='')),
                ('pic3', models.FileField(blank=True, null=True, upload_to='')),
                ('pic4', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProdSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('unit', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordertemp',
            name='customer_ID',
        ),
        migrations.RemoveField(
            model_name='ordertemp',
            name='order_ID',
        ),
        migrations.RemoveField(
            model_name='ordertemp',
            name='product_ID',
        ),
        migrations.RemoveField(
            model_name='orderby',
            name='customer_ID',
        ),
        migrations.RemoveField(
            model_name='orderby',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_06',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_06_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_07',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_07_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_08',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_08_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_09',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_09_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_10_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_11',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_11_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_12',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_12_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_13',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_13_5',
        ),
        migrations.AddField(
            model_name='orderby',
            name='user_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='register.Profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic_Format',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderTemp',
        ),
        migrations.AddField(
            model_name='prodsize',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='prod4',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='prod360',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
