# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20171026_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ID',
            field=models.CharField(default='', max_length=45, primary_key=True, serialize=False),
        ),
    ]
