# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20171027_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderby',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderby',
            name='order_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
