# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20171029_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderby',
            name='date_send',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='date delivered'),
        ),
    ]
