# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewS_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(default='', max_length=45)),
                ('comment', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField()),
                ('news_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.NewS')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(default='', max_length=45)),
                ('comment', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='orderby',
            name='post_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_Price_Sale',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='product_comment',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
