# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20171110_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='news_ID',
            field=models.CharField(default='', max_length=45, primary_key=True, serialize=False),
        ),
    ]
