# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='Profiles/PicCust_Default.png', upload_to='Profiles'),
        ),
    ]
